name = "RDD"
uuid = "e4b00b22-7947-11e9-33c8-1bc16e8482e2"
authors = ["Jonatan Sombi√© <jonatan.sombie@gmail.com>"]
version = "0.1.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
